service: hackaton-portunol

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: '*'
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
        - rekognition:IndexFaces
        - rekognition:SearchFacesByImage
      Resource: '*'

functions:
  findUserByFace:
    handler: handlers.findUserByFace
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: users/by-face
          method: post
          cors: true
  createUser:
    handler: handlers.createUser
    memorySize: 128
    timeout: 10
    environmentVariables:
      BUCKET_NAME: portunol-user-photos
      DYNAMO_TABLE: Users
    events:
      - http:
          path: users
          method: post
          cors: true
  playDiscountGame:
    handler: handlers.playDiscountGame
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: discounts
          method: post
          cors: true
